### ISSUE TITLE
Problema con el acceso HTTP - HTTPS

### ISSUE THREAD

**Issue by estebanarmas** [esri-es/ArcNotifier#15]
En la linea 294, del fichero de ArcNode.js en "node_modules/arc-node/" genera un erro al no poder acceder a los servicios utilizando http.

**Comment by hhkaos** [comment]
Añado de camino los problemas con el package.json :).thx

**Comment by hhkaos** [comment]
[He forzado](https://github.com/esri-es/ArcNode/commit/da8ea8982d23c2897bc7b1b0896e0e5b6cdad659) de momento a que las peticiones https se hagan con una URL https, esto arregla los problemas para ArcGIS Online pero puede dar problemas en instancias de server+portal que no usen certificados seguros.
